
package publicar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServices", targetNamespace = "http://publicar/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServices {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicar/WebServices/nuevoUsuarioRequest", output = "http://publicar/WebServices/nuevoUsuarioResponse")
    public void nuevoUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.DataUsuario
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/obtenerUsuarioRequest", output = "http://publicar/WebServices/obtenerUsuarioResponse")
    public DataUsuario obtenerUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns publicar.DataUsuarioArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar/WebServices/mostrarUsuariosRequest", output = "http://publicar/WebServices/mostrarUsuariosResponse")
    public DataUsuarioArray mostrarUsuarios();

}
